### ISSUE TITLE
Issue in preprocessing.py 

### ISSUE THREAD

**Issue by abduallahadel** [meownoid/face-identification-tpe#10]
Hello ,
I keep getting this error in 
```
preprocessing.py", line 18
    image, *,
            ^
SyntaxError: invalid syntax
```

I'm using python 3.6 and installed all dependencies .

I've been struggling all the day with this !

**Comment by meownoid** [comment]
It is strange. `*` is the standard Python syntax to indicate that all the parameters after this one should be named. And it works just fine fir me.

Anyway, you can change the function declaration to:
```

    def detect_faces(self,
                     image,
                     upscale_factor=1,
                     greater_than=None,
                     get_top=None):
```
Without any consequences.
