### ISSUE TITLE
What is the dev folder for?

### ISSUE THREAD

**Issue by Allmin** [meownoid/face-identification-tpe#11]
I can understand that the train and test file are for training and testing purposes. But what is the dev folder for?.  the dev/dev_protocol.npy file seems to be missing. how to get it. Thanks in advance.

**Comment by meownoid** [comment]
"Dev" stands for the "development". It is the same as validation set and is used to measure model's performance. `dev/dev_protocol.npy` can be built using the `utils/organize_data.py` script.
