### ISSUE TITLE
Some more detail information about training the model

### ISSUE THREAD

**Issue by diliphadoop742** [meownoid/face-identification-tpe#12]
Hello meownoid,

          Would you please let me know which dataset we need to use for training to getting better accuracy (other than lfw,caltech_faces,gt_db,fei) because the pre trained model is able to identify faces if the same image is passed to both load1 and load2 ?

i have applied Ms-celeba dataset for training the model after 19th epoch val_acc is not increasing and its value is 0.0084 , How can i increase the val_acc of the model???

**Comment by meownoid** [comment]
Repository is now archived, closing all issues.
