### ISSUE TITLE
Where is the file ' dev_protocol.npy'

### ISSUE THREAD

**Issue by Splendon** [meownoid/face-identification-tpe#19]
Hey，
I am very interested in this project, it is remarkable.
I try to do my best on this project, but I can't find the file  ' dev_protocol.npy'.
Also, I would like to ask that what the file of 'dev' will be used to do.
Thanks.

**Comment by deshaion** [comment]
You can find dev_protocol.npy [here](https://yadi.sk/d/16GictwI3ANWHv)
