### ISSUE TITLE
invalid syntax in line number 76 in models.py file

### ISSUE THREAD

**Issue by haridatascientist** [meownoid/face-identification-tpe#2]
1.i installed python3,
2. downloaded all the files and kept it in model directory.
3.run the demo_app1.py
i face the following issues:
File "demo_app1.py", line 24, in <module>
    from model import FaceVerificator
  File "/model.py", line 76
    scores = xs @ ys.T
                ^
SyntaxError: invalid syntax

**Comment by meownoid** [comment]
You should use python 3.5 or greater (@ operator was added in 3.5).
Or you can replace every expression `a @ b` to `np.matmul(a, b)`.
