### ISSUE TITLE
Could not download the needed files

### ISSUE THREAD

**Issue by maky-hnou** [meownoid/face-identification-tpe#21]
When I open the link to download the needed files, I could not download anything.  
All what I get in the page is some buttons that are **not working**!  
Is it a problem in the website?

**Comment by meownoid** [comment]
Yandex.Disk is one of the biggest cloud file storages, there should not be any problems. I highlighted the button that should start file downloading.

![yadisk](https://user-images.githubusercontent.com/20129246/55411987-4b072100-556f-11e9-97b3-b517d5119440.png)

**Comment by maky-hnou** [comment]
@meownoid , thank you. It seems to be an issue of Mozilla Firefox.  changed the browser and everything works fine. Now I can download the pretrained model.
Thank you.
