### ISSUE TITLE
can not run on OSX with PyQt5 issue

### ISSUE THREAD

**Issue by Aspirinkb** [meownoid/face-identification-tpe#3]
Hi there, I clone this repo on my mac which uses Anaconda, and pyqt5.5.0 is installed. When I run demo_app1.py, one error about PyQt5 comes out:
`Traceback (most recent call last):
  File "demo_app1.py", line 7, in <module>
    from PyQt5.QtWidgets import (
ImportError: dlopen(/Users/yan/anaconda/envs/face_identification_tpe/lib/python3.5/site-packages/PyQt5/QtWidgets.so, 2): Library not loaded: @rpath/./libicui18n.56.dylib
  Referenced from: /Users/yan/anaconda/envs/face_identification_tpe/lib/libQt5Core.5.5.0.dylib
  Reason: image not found`
Anyone help?

**Comment by meownoid** [comment]
Repository is now archived, closing all issues.
