### ISSUE TITLE
Cosine distance to Eula distance

### ISSUE THREAD

**Issue by zhuzzjlu** [meownoid/face-identification-tpe#8]
Hi, if i change the distance measurement from Cosine  to Eula, whether the algorithm is still effective.
Because this will greatly reduce the time complexity

**Comment by meownoid** [comment]
Can you please explain what is the eula distance exactly? Google didn't help me with that.

**Comment by zhuzzjlu** [comment]
Sorry，I didn't express it clearly, what I mean is Euclidean distance.
```
import numpy
dist = numpy.sqrt(numpy.sum(numpy.square(vec1 - vec2))) 
```

**Comment by meownoid** [comment]
1) Going for euclidean distance requires  the TPE loss function to be changed.
2) My experiments showed that cosine distance and corresponding loss function are more effective than the Euclidean distance.
3) If vectors are l2-normalized, euclidean distance and cosine distance are equivalent (you can check that expanding both of them).
4) As for time complexity, I don't think there is a lot of difference:
cosine = 2 normalizations, 1 multiplication
euclidean = 1 subtraction, 1 normalization, 1 multiplication, 1 square root
